name: smap-git publish

on:
  push:
    paths: smap-bin/*
  workflow_dispatch:

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish AUR package smap-git
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: smap-bin
          pkgbuild: smap-bin/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
